const { createServer } = require('http');
const { existsSync } = require('fs');
const { join } = require('path');
const next = require('next');

if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'production';
}

const port = Number.parseInt(process.env.PORT || '3000', 10);
const hostname = process.env.HOST || '0.0.0.0';
const dev = process.env.NODE_ENV === 'development';
const startedAt = new Date().toISOString();
const buildIdPath = join(process.cwd(), '.next', 'BUILD_ID');
const deploymentMarker = 'fast-boot-no-prelisten-build-2026-05-17-07';

let nextReady = false;
let nextPrepareError = null;
let handle = null;

function sendJson(res, statusCode, payload) {
  res.statusCode = statusCode;
  res.setHeader('content-type', 'application/json; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.end(JSON.stringify(payload, null, 2));
}

function sendHtml(res, statusCode, title, message, details) {
  res.statusCode = statusCode;
  res.setHeader('content-type', 'text/html; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a;margin:0;padding:32px}main{max-width:980px;margin:auto;background:#fff;border:1px solid #dbe3ef;border-radius:24px;padding:28px;box-shadow:0 20px 50px rgba(15,23,42,.1)}h1{margin-top:0}pre{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:18px;border-radius:16px;overflow:auto}.badge{display:inline-block;background:#dbeafe;color:#1e40af;border-radius:999px;padding:6px 10px;font-weight:700}</style></head><body><main><span class="badge">Runtime diagnostic</span><h1>${title}</h1><p>${message}</p><pre>${details}</pre></main></body></html>`);
}

function runtimePayload() {
  return {
    app: 'Competitive Intelligence Hub',
    deploymentMarker,
    ok: nextReady,
    status: nextReady ? 'Next.js ready' : 'Node server is listening, Next.js is not ready yet',
    nodeVersion: process.version,
    nodeEnv: process.env.NODE_ENV,
    hostname,
    port,
    cwd: process.cwd(),
    buildIdPath,
    buildExists: existsSync(buildIdPath),
    nextPrepareError: nextPrepareError ? String(nextPrepareError.stack || nextPrepareError.message || nextPrepareError) : null,
    startedAt,
    guidance: [
      'This response is generated by server.js, which means Hostinger is reaching the Node process.',
      'The server binds to the port immediately and does not run npm build before listening.',
      'If buildExists is false, Hostinger did not run or preserve npm run build output.',
      'Confirm Hostinger application root is the repository root.',
      'Confirm build command is npm install && npm run build.',
      'Confirm start command is npm start and startup file is server.js.',
      'Do not manually set PORT unless Hostinger explicitly requires it.'
    ]
  };
}

function apiRouteProbe(pathname) {
  return {
    ...runtimePayload(),
    route: pathname,
    message: 'server.js API JSON guard is active. If this route returns JSON, Hostinger is reaching Node instead of serving an HTML fallback.',
    expectedNextApiRoute: pathname === '/api/analyze' ? 'app/api/analyze/route.ts' : null
  };
}

const app = next({ dev, hostname, port });

const server = createServer((req, res) => {
  const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);

  if (url.pathname === '/__startup') {
    return sendJson(res, 200, runtimePayload());
  }

  if (!nextReady || !handle) {
    if (url.pathname.startsWith('/api/')) {
      return sendJson(res, 200, apiRouteProbe(url.pathname));
    }
    return sendHtml(res, 200, 'Competitive Intelligence Hub is starting', 'The Node process is alive. Next.js is still preparing or failed to prepare. Details are below.', JSON.stringify(runtimePayload(), null, 2));
  }

  if (req.method === 'GET' && ['/api/version', '/api/health', '/api/diagnostics', '/api/analyze'].includes(url.pathname)) {
    return sendJson(res, 200, apiRouteProbe(url.pathname));
  }

  if (req.method === 'HEAD' && url.pathname.startsWith('/api/')) {
    res.statusCode = 200;
    res.setHeader('content-type', 'application/json; charset=utf-8');
    res.end();
    return;
  }

  if (url.pathname.startsWith('/api/')) {
    res.setHeader('x-cih-api-guard', deploymentMarker);
  }

  return handle(req, res);
});

server.on('error', (listenError) => {
  console.error('Competitive Intelligence Hub server failed to bind.', listenError);
  process.exit(1);
});

server.listen(port, hostname, () => {
  console.log(`Competitive Intelligence Hub fast boot server listening on ${hostname}:${port} in ${dev ? 'development' : 'production'} mode with ${deploymentMarker}`);
});

app.prepare()
  .then(() => {
    handle = app.getRequestHandler();
    nextReady = true;
    console.log('Competitive Intelligence Hub Next.js app prepared successfully.');
  })
  .catch((error) => {
    nextPrepareError = error;
    nextReady = false;
    console.error('Competitive Intelligence Hub Next.js app failed to prepare.', error);
  });
