const { createServer } = require('http');
const { existsSync } = require('fs');
const { join } = require('path');

if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'production';
}

process.env.NEXT_TELEMETRY_DISABLED = '1';

const parsedPort = Number.parseInt(process.env.PORT || '3000', 10);
const port = Number.isFinite(parsedPort) && parsedPort > 0 ? parsedPort : 3000;
const requestedHost = process.env.CIH_BIND_HOST || process.env.BIND_HOST || '0.0.0.0';
const hostname = ['0.0.0.0', '127.0.0.1', 'localhost', '::'].includes(requestedHost) ? requestedHost : '0.0.0.0';
const ignoredHost = process.env.HOST && process.env.HOST !== hostname ? process.env.HOST : null;
const dev = process.env.NODE_ENV === 'development';
const startedAt = new Date().toISOString();
const projectRoot = process.cwd();
const buildIdPath = join(projectRoot, '.next', 'BUILD_ID');
const deploymentMarker = 'hostinger-safe-bind-2026-05-18-05';

let nextReady = false;
let nextPreparing = false;
let nextPrepareStartedAt = null;
let nextPrepareFinishedAt = null;
let nextPrepareError = null;
let handle = null;
let commandLog = [];

function rememberLog(line) {
  const cleanLine = String(line || '').trimEnd();
  if (!cleanLine) return;
  commandLog.push(cleanLine);
  if (commandLog.length > 120) {
    commandLog = commandLog.slice(commandLog.length - 120);
  }
}

function htmlEscape(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function sendJson(res, statusCode, payload) {
  if (res.headersSent) return;
  res.statusCode = statusCode;
  res.setHeader('content-type', 'application/json; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.setHeader('x-cih-runtime', deploymentMarker);
  res.end(JSON.stringify(payload, null, 2));
}

function sendHtml(res, statusCode, title, message, details) {
  if (res.headersSent) return;
  res.statusCode = statusCode;
  res.setHeader('content-type', 'text/html; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.setHeader('x-cih-runtime', deploymentMarker);
  res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${htmlEscape(title)}</title><style>body{font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a;margin:0;padding:32px}main{max-width:980px;margin:auto;background:#fff;border:1px solid #dbe3ef;border-radius:24px;padding:28px;box-shadow:0 20px 50px rgba(15,23,42,.1)}h1{margin-top:0}pre{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:18px;border-radius:16px;overflow:auto}.badge{display:inline-block;background:#dbeafe;color:#1e40af;border-radius:999px;padding:6px 10px;font-weight:700}</style></head><body><main><span class="badge">Runtime diagnostic</span><h1>${htmlEscape(title)}</h1><p>${htmlEscape(message)}</p><pre>${htmlEscape(details)}</pre></main></body></html>`);
}

function runtimePayload(extra = {}) {
  return {
    app: 'Competitive Intelligence Hub',
    deploymentMarker,
    ok: nextReady,
    status: nextReady ? 'Next.js ready' : 'Node server is listening while Next.js prepares',
    nodeVersion: process.version,
    nodeEnv: process.env.NODE_ENV,
    hostname,
    ignoredHost,
    port,
    rawPort: process.env.PORT || null,
    cwd: projectRoot,
    buildIdPath,
    buildExists: existsSync(buildIdPath),
    nextReady,
    nextPreparing,
    nextPrepareStartedAt,
    nextPrepareFinishedAt,
    nextPrepareError: nextPrepareError ? String(nextPrepareError.stack || nextPrepareError.message || nextPrepareError) : null,
    commandLog,
    startedAt,
    guidance: [
      'This response is generated by server.js, which means Hostinger reached the Node process.',
      'This server intentionally ignores HOST unless CIH_BIND_HOST or BIND_HOST is set to a bindable interface.',
      'Hostinger should run npm run build to create .next, then npm run start to launch this file.',
      'Use /api/runtime or /__startup to confirm whether Node is listening and whether Next.js prepared successfully.'
    ],
    ...extra
  };
}

async function prepareNext() {
  if (nextReady || nextPreparing) return;

  nextPreparing = true;
  nextPrepareStartedAt = new Date().toISOString();
  nextPrepareFinishedAt = null;
  nextPrepareError = null;
  rememberLog(`[${nextPrepareStartedAt}] Preparing Next.js application.`);

  try {
    const next = require('next');
    const app = next({ dev, hostname: '0.0.0.0', port });
    await app.prepare();
    handle = app.getRequestHandler();
    nextReady = true;
    nextPrepareError = null;
    rememberLog(`[${new Date().toISOString()}] Next.js prepared successfully.`);
  } catch (error) {
    nextReady = false;
    handle = null;
    nextPrepareError = error;
    rememberLog(`[${new Date().toISOString()}] Next.js prepare failed: ${String(error && (error.stack || error.message) || error)}`);
  } finally {
    nextPreparing = false;
    nextPrepareFinishedAt = new Date().toISOString();
  }
}

function apiRouteProbe(pathname, method) {
  return runtimePayload({
    route: pathname,
    method,
    message: 'server.js API JSON guard is active while Next.js prepares.'
  });
}

function readRequestBody(req, maxBytes = 1024 * 1024) {
  return new Promise((resolve) => {
    const chunks = [];
    let total = 0;
    req.on('data', (chunk) => {
      total += chunk.length;
      if (total <= maxBytes) chunks.push(Buffer.from(chunk));
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', () => resolve(''));
  });
}

const server = createServer(async (req, res) => {
  let url;
  try {
    url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);
  } catch (error) {
    return sendJson(res, 400, runtimePayload({ error: 'Invalid request URL', detail: String(error) }));
  }

  try {
    if (url.pathname === '/__startup' || url.pathname === '/api/runtime') {
      return sendJson(res, 200, runtimePayload({ route: url.pathname, method: req.method }));
    }

    if (!nextReady || !handle) {
      prepareNext();

      if (url.pathname.startsWith('/api/')) {
        return sendJson(res, 200, apiRouteProbe(url.pathname, req.method || 'GET'));
      }

      return sendHtml(
        res,
        200,
        'Competitive Intelligence Hub is starting',
        'The Node process is alive. Next.js is preparing from the built .next output. This page prevents Hostinger from showing a 503 while startup finishes.',
        JSON.stringify(runtimePayload(), null, 2)
      );
    }

    if (req.method === 'POST' && url.pathname === '/api/analyze' && url.searchParams.get('runtimeProbe') === '1') {
      const body = await readRequestBody(req);
      return sendJson(res, 200, runtimePayload({
        route: url.pathname,
        method: req.method,
        bodyBytesReceived: Buffer.byteLength(body),
        message: 'POST /api/analyze reached server.js and returned JSON. Remove runtimeProbe=1 to run the real Next API analysis route.'
      }));
    }

    if (req.method === 'HEAD' && url.pathname.startsWith('/api/')) {
      res.statusCode = 200;
      res.setHeader('content-type', 'application/json; charset=utf-8');
      res.setHeader('x-cih-runtime', deploymentMarker);
      res.end();
      return;
    }

    if (url.pathname.startsWith('/api/')) {
      res.setHeader('x-cih-api-guard', deploymentMarker);
    }

    return handle(req, res);
  } catch (error) {
    rememberLog(`[${new Date().toISOString()}] Request handling failed: ${String(error && (error.stack || error.message) || error)}`);
    if (url.pathname.startsWith('/api/')) {
      return sendJson(res, 500, runtimePayload({
        route: url.pathname,
        method: req.method,
        error: 'Request handling failed',
        detail: String(error && (error.stack || error.message) || error)
      }));
    }
    return sendHtml(
      res,
      500,
      'Competitive Intelligence Hub request failed',
      'The Node process is alive, but a request handler failed. Runtime details are shown below instead of allowing a generic 503.',
      JSON.stringify(runtimePayload({ detail: String(error && (error.stack || error.message) || error) }), null, 2)
    );
  }
});

server.on('error', (listenError) => {
  console.error('Competitive Intelligence Hub server failed to bind.', listenError);
  process.exit(1);
});

process.on('uncaughtException', (error) => {
  console.error('Competitive Intelligence Hub uncaught exception.', error);
  rememberLog(`[${new Date().toISOString()}] Uncaught exception: ${String(error && (error.stack || error.message) || error)}`);
});

process.on('unhandledRejection', (error) => {
  console.error('Competitive Intelligence Hub unhandled rejection.', error);
  rememberLog(`[${new Date().toISOString()}] Unhandled rejection: ${String(error && (error.stack || error.message) || error)}`);
});

server.listen(port, hostname, () => {
  const message = `Competitive Intelligence Hub server listening on ${hostname}:${port} in ${dev ? 'development' : 'production'} mode with ${deploymentMarker}`;
  console.log(message);
  rememberLog(`[${new Date().toISOString()}] ${message}`);
  prepareNext();
});
